version: "2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: umamaheshdocker/get-started:1
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
